services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_RESTRICT_FILE_ACCESS_TO=/data/rules
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - n8n_data:/home/node/.n8n
      - ../rules:/data/rules:ro
      - ./resolv.conf:/etc/resolv.conf:ro

volumes:
  n8n_data:
